# Generated by Django 2.2.10 on 2020-02-28 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concrete', '0003_delete_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concrete_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, default='', max_length=250)),
                ('resource_status', models.CharField(blank=True, choices=[('to-send', 'Email should be sent'), ('send-in-progress', 'Email sending'), ('send-error', 'Error during sending'), ('sent', 'Email sent')], default='to-send', max_length=250)),
                ('resource_message', models.CharField(blank=True, default='', max_length=250)),
                ('body', models.TextField(blank=True, default='')),
                ('additional_filtering', models.BooleanField(default=False)),
                ('can_admin_groups', models.ManyToManyField(blank=True, related_name='group_administrable_emails', to='concrete_auth.Group')),
                ('can_admin_users', models.ManyToManyField(blank=True, related_name='administrable_emails', to=settings.AUTH_USER_MODEL)),
                ('can_view_groups', models.ManyToManyField(blank=True, related_name='group_viewable_emails', to='concrete_auth.Group')),
                ('can_view_users', models.ManyToManyField(blank=True, related_name='viewable_emails', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_emails', to=settings.AUTH_USER_MODEL)),
                ('defaultdivider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divider_emails', to='concrete.DefaultDivider')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
