# Generated by Django 2.2.10 on 2020-02-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0002_auto_20200228_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
